
MANDIR=/usr/share/man

all:

install:
	mkdir -p $(INSTROOT)$(MANDIR)/man8
	install -m 644 en/redhat-config-kickstart.8 $(INSTROOT)$(MANDIR)/man8
	mkdir -p $(INSTROOT)$(MANDIR)/ja/man8
	install -m 644 ja/redhat-config-kickstart.8 $(INSTROOT)$(MANDIR)/ja/man8

clean:
