.TH SYSTEM-CONFIG-KICKSTART 8 "Wed 13 June 2001" "Linux" "Kickstart Configurator"
.UC 4
.SH NAME
system-config-kickstart \- graphical interface for creating kickstart files
.SH SYNOPSIS
\fBsystem-config-kickstart\fR 
.SH DESCRIPTION
\fBsystem-config-kickstart\fR provides a simple method of creating a kickstart file that can be used to automate the installation process on Red Hat Linux.

.SH OPTIONS 
None
.SH FILES
\fI/usr/bin/system-config-kickstart\fP
.br
\fI/usr/share/system-config-kickstart/*\fP
.br
.SH EXAMPLES
To run the program type:
.LP
system-config-kickstart
.LP

.SH "REPORTING BUGS"
Report bugs to <http://bugzilla.redhat.com>.

.SH AUTHORS
.nf
Brent Fox <bfox@redhat.com>
Tammy Fox <tfox@redhat.com>
.fi






