.TH KSCONFIG 8 "Wed 13 June 2001" "Linux" "Kickstart Configurator"
.UC 4
.SH 名前
ksconfig \- キックスタートファイルを作成するグラフィカルなインターフェース
.SH 書式
\fBksconfig\fR 
.SH 説明
\fBksconfig\fR ではRed Hat Linuxのインストールを自動化するキックスタートの
ファイルをシンプルに作成することができます。

.SH オプション
なし
.SH ファイル
\fI/usr/sbin/ksconfig\fP
.br
\fI/usr/share/ksconfig/*\fP
.br
.SH 実行例
プログラムを実行するには:
.LP
ksconfig
.LP
と入力してください。

.SH バグレポート
バグは<http://bugzilla.redhat.com>にレポートしてください。

.SH 著者
.nf
Brent Fox <bfox@redhat.com>
Tammy Fox <tfox@redhat.com>
.fi






