#define languages, add languages here
langDict = {"Chinese(Mainland)" :  "zh_CN.GB2312",
                 "Chinese(Taiwan)" : "zh_TW.Big5",
                 "Czech" : "cs_CZ",
                 "Danish" : "da_DK",
                 "English" : "en_US",
                 "French" : "fr_FR",
                 "German" : "de_DE",
                 "Icelandic" : "is_IS",
                 "Italian" : "it_IT",
                 "Japanese" : "ja_JP.eucJP",
                 "Korean" : "ko_KR.eucKR",
                 "Norwegian" : "no_NO",
                 "Portuguese" : "pt_PT",
                 "Russian" : "ru_RU.k0I8r",
                 "Slovenian" : "sl_SI",
                 "Spanish" : "es_ES",
                 "Swedish" : "sv_SE",
                 "Ukrainian" : "uk_UA",
            }

#define mice, add mice here
mouseDict = { "No Mouse" : "none",
                   "ALPS GlidePoint (PS/2)" : "alpsps/2",
                   "ASCII MieMouse (serial)" : "ascii",
                   "ASCII MieMouse (PS/2)" : "asciips/2",
                   "ATI Bus Mouse" : "atibm",
                   "Generic Mouse (serial)" : "generic",
                   "Generic 3 Button Mouse (serial)" : "generic3",
                   "Generic Mouse (PS/2)" : "genericps/2",
                   "Generic 3 Button Mouse (PS/2)" : "generic3ps/2",
                   "Generic Mouse (USB)" : "genericusb",
                   "Generic 3 Button Mouse (USB)" : "generic3usb",
                   "Genius NetMouse (serial)" : "geniusnm",
                   "Genius NetMouse (PS/2)" : "geniusnmps/2",
                   "Genius NetMouse Pro (PS/2)" : "geniusprops/2",
                   "Genius NetScroll (PS/2)" : "geniusscrollps/2",
                   "Kensington Thinking Mouse (serial)" : "thinking",
                   "Kensington Thinking Mouse (PS/2)" : "thinkingps/2",
                   "Logitech Mouse (serial, old C7 type)" : "logitech",
                   "Logitech CC Series (serial)" : "logitechcc",
                   "Logitech Bus Mouse" : "logibm",
                   "Logitech MouseMan/FirstMouse (serial)" : "logimman",
                   "Logitech MouseMan/FirstMouse (PS/2)" : "logimmanps/2",
                   "Logitech MouseMan+/FirstMouse+ (serial)" : "logimman+",
                   "Logitech MouseMan+/FirstMouse+ (PS/2)" : "logimman+ps/2",
                   "Logitech MouseMan Wheel (USB)" : "logimmusb",
                   "Microsoft compatible (serial)" : "microsoft",
                   "Microsoft Rev 2.1A or higher (serial)" : "msnew",
                   "Microsoft IntelliMouse (serial)" : "msintelli",
                   "Microsoft IntelliMouse (PS/2)" : "msintellips/2",
                   "Microsoft IntelliMouse (USB)" : "msintelliusb",
                   "Microsoft Bus Mouse" : "msbm",
                   "Mouse Systems (serial)" : "mousesystems",
                   "MM Series (serial)" : "mmseries",
                   "MM HitTablet (serial)" : "mmhittab",
                   "Sun Mouse" : "sun",
                   }
