#!/usr/bin/python

import string

class KickstartData:
    def __init__(self):
        self.lang = None
        self.langsupport = None
        self.defaultLang = None
        self.keyboard = None
        self.mouse = None
        self.timezone = None
        self.rootpw = None
        self.reboot = None
        self.install = None
        self.cdrom = None
        self.bootloader = None
        self.zerombr = None
        self.clearpart = None
        self.network = None
        self.auth = None
        self.firewall = None
        self.skipx = None
        self.packages = None
        self.pre = None
        self.post = None

    def setLang(self, args):
        self.lang = args[0]

    def getLang(self):
        return self.lang

    def setLangsupport(self, args):
        list = []

        for item in args:
            if item[:10] == "--default=":
                self.defaultLang = item[10:]
            else:
                list.append(item)

        self.langsupport = list

    def getLangsupport(self):
        return self.langsupport
        
    def setKeyboard(self, args):
        self.keyboard = args[0]

    def getKeyboard(self):
        return self.keyboard

    def setMouse(self, args):
        self.mouse = args[0]

    def getMouse(self):
        return self.mouse

    def setTimezone(self, args):
        self.timezone = args

    def getTimezone(self):
        return self.timezone

    def setRootPw(self, args):
        self.rootpw = args

    def getRootPw(self):
        return self.rootpw

    def setReboot(self, args):
        self.reboot = "reboot"

    def getReboot(self):
        return self.reboot 
    
    def setInstall(self, args):
        self.install = "install"

    def getInstall(self):
        return self.install

    def setCdrom(self, args):
        self.cdrom = "cdrom"

    def getCdrom(self):
        return self.cdrom

    def setBootloader(self, args):
        self.bootloader = args

    def getBootloader(self):
        return self.bootloader

    def setZeroMbr(self, args):
        self.zerombr = args

    def getZeroMbr(self):
        return self.zerombr

    def setClearPart(self, args):
        self.clearpart = args

    def getClearPart(self):
        return self.clearpart

    def setNetwork(self, args):
        self.network = args

    def getNetwork(self):
        return self.network

    def setAuth(self, args):
        self.auth = args

    def getAuth(self):
        return self.auth

    def setFirewall(self, args):
        self.firewall = args

    def getFirewall(self):
        return self.firewall

    def setSkipX(self, args):
        self.skipx = args

    def getSkipX(self):
        return self.skipx

    def getAll(self):
        print "in getAll"
        file = []

        file.append("#Generated by Kickstart Configurator\n")
        file.append("#System  language")
        file.append("lang %s" % self.getLang())

        file.append("#Language modules to install")
        if len(self.langsupport) == 0:
            file.append("langsupport --default=" + self.defaultLang)

        elif len(self.langsupport) > 0:
            list = string.join(self.langsupport, " ")
            file.append("langsupport " + list + " --default=" + self.defaultLang)
##             if len(self.langsupport) ==  1:
##                 file.append("langsupport " + list + " --default " + defaultLang)

##             else:
##                 if defaultLang in lang_list:                
##                     data.append("langsupport " + list + " --default " + defaultLang)
##                 else:
##                     list = list + " " + defaultLang
##                     data.append("langsupport " + list + " --default " + defaultLang)

#        file.append("langsupport 



        for line in file:
            print line
    

#        return file
