#!/usr/bin/python

import string

class KickstartData:
    def __init__(self):
        self.lang = None
        self.langsupport = None
        self.defaultLang = None
        self.keyboard = None
        self.mouse = None
        self.timezone = None
        self.rootpw = None
        self.reboot = None
        self.install = None
        self.interactive = None
        self.text = None
        self.cdrom = None
        self.bootloader = None
        self.zerombr = None
        self.clearpart = None
        self.network = None
        self.auth = None
        self.firewall = None
        self.skipx = None
        self.packages = None
        self.pre = None
        self.post = None

    def setLang(self, args):
        self.lang = args[0]

    def getLang(self):
        return self.lang

    def setLangSupport(self, args):
        list = []

        for item in args:
            if item[:10] == "--default=":
                self.setDefaultLang(item[10:])
            else:
                list.append(item)

        self.langsupport = list

    def getLangSupport(self):
        return self.langsupport
        
    def setDefaultLang(self, default):
        self.defaultLang = default

    def getDefaultLang(self):
        return self.defaultLang

    def setKeyboard(self, args):
        self.keyboard = args[0]

    def getKeyboard(self):
        return self.keyboard

    def setMouse(self, args):
        self.mouse = args[0]

    def getMouse(self):
        return self.mouse

    def setText(self, args):
        self.text = args[0]

    def getText(self):
        return self.text

    def setTimezone(self, args):
        self.timezone = args[-1]

    def getTimezone(self):
        return self.timezone

    def setRootPw(self, args):
        self.rootpw = string.join(args, " ")

    def getRootPw(self):
        return self.rootpw

    def setReboot(self, args):
        self.reboot = args[0]

    def getReboot(self):
        return self.reboot 
    
    def setInstall(self, args):
        self.install = args

    def getInstall(self):
        return self.install

    def setInteractive(self, args):
        self.interactive = args[0]

    def getInteractive(self):
        return self.interactive

    def setCdrom(self, args):
        self.cdrom = "cdrom"

    def getCdrom(self):
        return self.cdrom

    def setBootloader(self, args):
        self.bootloader = args

    def getBootloader(self):
        return self.bootloader

    def setZeroMbr(self, args):
        self.zerombr = args

    def getZeroMbr(self):
        return self.zerombr

    def setClearPart(self, args):
        self.clearpart = args

    def getClearPart(self):
        return self.clearpart

    def setNetwork(self, args):
        self.network = args

    def getNetwork(self):
        return self.network

    def setAuth(self, args):
        self.auth = args

    def getAuth(self):
        return self.auth

    def setFirewall(self, args):
        self.firewall = args

    def getFirewall(self):
        return self.firewall

    def setSkipX(self, args):
        self.skipx = args

    def getSkipX(self):
        return self.skipx

    def getAll(self):
        print "in getAll\n\n"
        file = []

        file.append("#Generated by Kickstart Configurator\n")
        file.append("#System  language")
        file.append("lang %s" % self.getLang())

        file.append("#Language modules to install")
        if len(self.langsupport) == 0:
            file.append("langsupport --default=" + self.getDefaultLang())

        elif len(self.langsupport) > 0:
            if self.getDefaultLang() in self.getLangSupport():
                self.langsupport.remove(self.getDefaultLang())
                            
            list = string.join(self.langsupport, " ")
            file.append("langsupport " + list + " --default=" + self.getDefaultLang())

        file.append("#System keyboard")
        file.append("keyboard " + self.getKeyboard())
        file.append("#System mouse")
        file.append("mouse " + self.getMouse())
        file.append("#Sytem timezone")
        file.append("timezone --utc " + self.getTimezone())
        file.append("#Root password")
        file.append("rootpw " + self.getRootPw())

        
        if self.getReboot():
            file.append("#Reboot after installation")
            file.append(self.getReboot())

        if self.getText():
            file.append("#Use text mode install")
            file.append(self.getText())

        if self.getInteractive():
            file.append("#Use interactive kickstart installation method")
            file.append(self.getInteractive())



        for line in file:
            print line
    

#        return file
